language: ruby
before_install: "gem install bundler"
script: "bundle exec rake"
notifications:
  email:
    - alessiorocco@nebulab.it
branches:
  only:
    - master
rvm:
  - 2.4.1
  - 2.3.3
  - 2.2.3
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
addons:
  code_climate:
    repo_token: 7e49a138186c8d4d5eb6632586252a17f794ebeb765e013bc8363c4efffd34c5
after_success:
  - bundle exec codeclimate-test-reporter
